### ISSUE TITLE
Laravel package

### ISSUE THREAD

**Issue by suleymanozev** [archtechx/enums#10]
It would be great if a separate package is made for laravel.

e.g. Command for enum annotate method tag

``` php
  /**
   * @method static SUPER_ADMIN()
   * @method static ADMIN()
   */
  enum RoleName: string
  {
      use InvokableCases;
  
      case SUPER_ADMIN = 'SUPER_ADMIN';
      case ADMIN = 'ADMIN';
  }
```

**Comment by stancl** [comment]
What concrete Laravel-specific features could this package have?

**Comment by suleymanozev** [comment]
Create enums:
`php artisan make:enum --invokable`
Annotate enum:
`php artisan enum:annotate RoleName`

**Comment by suleymanozev** [comment]
Localized enum

**Comment by muasx88** [comment]
nice ide, i need it to include in my migrations file.

i tried this:
 
```$table->enum('status', EnumOfStatus::value());```

but got the error: Class "EnumOfStatus" not found

**Comment by stancl** [comment]
Likely won't implement this in this package since I want it to be pure PHP, with no Laravel dependencies.

Later on we might create a `laravel-enums` package that includes this stuff on top of the core `enums` package 👍🏻 Thanks for the suggestions!
