### ISSUE TITLE
interface implementations

### ISSUE THREAD

**Issue by nicxlau** [archtechx/enums#17]
would it be good to implement the interface to identify if the enum has the trait Values, Names..?

Example

````php
use ArchTech\Enums\Names;
use ArchTech\Enums\Traits\Nameable;

enum TaskStatus: int implements Nameable
{
    use Names;

    case INCOMPLETE = 0;
    case COMPLETED = 1;
    case CANCELED = 2;
}

```

**Comment by stancl** [comment]
> would it be good

If you can list use cases where the benefit of that would outweigh the added complexity.
