### ISSUE TITLE
Return case value when calling the case

### ISSUE THREAD

**Issue by AbdulkarimOmer** [archtechx/enums#24]
let's assume we have an enum for seat status:

```
enum SeatStatusEnum: string
{
    case AVAILABLE = 'available';

    case RESERVED = 'reserved';
}
```

if I want to get AVAILABLE case value, I have to call the value property like this:
`SeatStatusEnum::AVAILABLE->value
`
if there is a treat that automatically retrieves case value when calling the case without calling the value property, it would be great.

**Comment by stancl** [comment]
See the README
