### ISSUE TITLE
ArchTech\Enums\Options::stringOptions():

### ISSUE THREAD

**Issue by xgbnl** [archtechx/enums#26]
When I try to run the php artisan command in my project, it prompts this error:
Deprecated: ArchTech\Enums\Options::stringOptions(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/my_project_api/vendor/archtechx/enums/src/Options.php on line 26

**Comment by rk4an** [comment]
Hello,

Same issue, warning reported when I run Laravel Pint and using Laravel-Lang and PHP 8.4:

ArchTech\Enums\Options::stringOptions(): Implicitly marking parameter $callback as nullable is deprecated

**Comment by szepeviktor** [comment]
Fixed in  #25

**Comment by stancl** [comment]
Tagged a new version now 👍 https://github.com/archtechx/enums/releases/tag/v1.1.1
