### ISSUE TITLE
fromName() & tryFromName()

### ISSUE THREAD

**Issue by stancl** [archtechx/enums#4]
To instantiate a backed enum using the case name.

Perhaps passing a callback would also work, if transformations or comparisons are needed (e.g. I have a use case that does `strtoupper()` to convert the readable version to the case name).

**Comment by iamharis010** [comment]
The behaviour of these methods will be similar to from() and tryFrom() in PHP ? @stancl 

Only the difference will be fromName() will take a case name as an input & return its value or throw Exception if value not found, while tryFromName() will return null instead of exception right ?

**Comment by samlev** [comment]
You can add those methods to a Pure enum with a trait:

```php
static public function from(string $case)
{
    return static::tryFrom($case)
        ?? throw new \ValueError(__CLASS__ . '::' . $case . ' does not exist');
}

static public function tryFrom(string $case)
{
    $cases = array_filter(static::cases(), fn($c) => $c->name === $case);
    return array_pop($cases) ?? null;
}
```

They will throw a fatal error if you try to define them on a backed enum (because they already exist), but with a trait they simply get ignored.

[See it in action](https://3v4l.org/MQLih)
